### ISSUE TITLE
Still prompts for admin creds

### ISSUE THREAD

**Issue by keithemyers** [aduffner/uninstallMacApps#1]
Hi, thanks for putting this out there! I'm getting an admin prompt when I click on "Delete". 

"Finder wants to move 3 items to the trash".

I'm attempting to delete BBEdit, the same app as in your example. Users are non-admins. Do you know how to correct this?

**Comment by aduffner** [comment]
@keithemyers How you deploy it, through an MDM like Jamf or just testing it locally?

**Comment by keithemyers** [comment]
Jamf as a Self Service policy.

**Comment by keithemyers** [comment]
The test computer is macOS 14.5 btw.

**Comment by keithemyers** [comment]
I was able to get this working by commenting out line #186 and adding this below it:

`  for appsToDel in ${paths[@]}; do `
`    echo "Deleting ${appsToDel}" `
`    rm -rf "$appsToDel" `
`  done `

The remainder of your script continues at line #191 (echo "Done").
